apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-depl
spec:
  selector:
    matchLabels:
      app: music
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
        - name: music
          image: alexandraioan/music-service
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8006
---

apiVersion: v1
kind: Service
metadata:
  name: music-clusterip-srv
spec:
  selector:
    app: music
  ports:
    - name: music
      protocol: TCP
      port: 8006
      targetPort: 8006