apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-depl
spec:
  selector:
    matchLabels:
      app: music
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
        - name: music
          image: alexandraioan/music-service
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8006

---

apiVersion: v1
kind: Service
metadata:
  name: music-clusterip-srv
spec:
  type: LoadBalancer
  selector:
    app: music
  ports:
    - name: music
      protocol: TCP
      port: 8006
      targetPort: 8006

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: musicdb-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: musicdb
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 400Mi
